#!/bin/bash

run() {
  dir=$1
  day=$(basename "$dir")
  echo "$day"
  if [ -f "$dir/${day//d/D}.hs" ]; then
    runhaskell "$dir/${day//d/D}.hs" < "$dir/input.txt"
  elif [ -f "$dir/$day.sh" ]; then
    bash "$dir/$day.sh" < "$dir/input.txt"
  else
    echo "Failed to run $day"
  fi
  echo
}

export -f run

find . -name 'day*' -type d -exec bash -c 'run "$@"' bash {} \;
